services:
  redis1:
    image: redis:latest
    container_name: redis1
    command: ['redis-server', '--appendonly', 'yes']
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -c PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - "6379:6379"

  redis2:
    image: redis:latest
    container_name: redis2
    command: ['redis-server', '--appendonly', 'yes', '--port', '6380']
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6380 -c PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - "6380:6380"

  redis-riot:
    build:
      context: ./riot
    container_name: redis-riot
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
    restart: "unless-stopped"

  redis-riotx:
    build:
      context: ./riotx
    container_name: redis-riotx
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
    restart: "unless-stopped"

  redis-migration:
    build:
      context: ./migration
    container_name: redis-migration
    depends_on:
      redis1:
        condition: service_healthy
    restart: "no"
