FROM alpine/java:22-jdk

ARG VERSION=4.2.3

RUN wget https://github.com/redis-field-engineering/riotx-dist/releases/download/v${VERSION}/riotx-${VERSION}.zip && unzip riotx-${VERSION}.zip 
WORKDIR /riotx-${VERSION}/bin/

ENTRYPOINT ["tail", "-f", "/dev/null"]
